input:
  generate:
    mapping: 'root = {"first_name":fake("first_name"), "last_name":fake("last_name"), "age":random_int(min:0, max:99)}'
    interval: 1ns
    count: 1000
    batch_size: 1
    auto_replay_nacks: true

output:
  sql_insert:
    driver: postgres
    dsn: postgresql://user:password@postgres:5432/db?sslmode=disable
    table: test_data
    columns:
      - first_name
      - last_name
      - age
    args_mapping: |
        root = [
          this.first_name,
          this.last_name,
          this.age
        ]
    init_statement: |
        CREATE TABLE IF NOT EXISTS test_data (
          id SERIAL PRIMARY KEY,
          first_name VARCHAR(255),
          last_name VARCHAR(255),
          age INT
        );
