input:
  generate:
    mapping: root = {"TID":"1001", "AGE":12, "F1":12.66}
    count: 1

output:
  sql_insert:
    driver: oracle
    dsn: oracle://system:testpass@localhost:58949/FREEPDB1
    table: test
    columns: [ TID, AGE, F1 ]
    args_mapping: |
      root = [ this.TID, this.AGE, this.F1 ]
    max_in_flight: 1
    init_statement: CREATE TABLE test (TID varchar(255), AGE int, F1 float)
    batching:
      count: 500
      period: 100ms