input:
  http_server:
    path: /post
    allowed_verbs:
      - POST
    timeout: 5s
    sync_response:
      status: 200

pipeline:
  processors:
    - sleep:
        duration: 1s

    - log: 
        message: "NAME RECEIVED: ${! this.name}"
        level: WARN

    - mapping: |
        root = {"message": "Hello " + this.name}

    

output:
  sync_response: {}
