input:
  stdin: {}
  
pipeline:
  processors:
    - bloblang: |
        root.val =  env("myMap")
    - mapping: |
        root = this
        root.new = root.val.trim("\"").parse_json()

output:
  stdout: {}